FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    pkg-config \
    libaio-dev \
    libblkid-dev \
    libkeyutils-dev \
    liblz4-dev \
    libscrypt-dev \
    libsodium-dev \
    liburcu-dev \
    libzstd-dev \
    uuid-dev \
    zlib1g-dev \
    valgrind

WORKDIR /build
RUN git clone https://github.com/koverstreet/bcachefs-tools.git .
RUN make -j5 && make install
