FROM archlinux:latest

RUN pacman --noconfirm -Sy \
    base-devel \
    git \
    libaio \
    keyutils \
    libsodium \
    liburcu \
    zstd \
    valgrind

RUN mkdir -p /build
RUN cd /build && git clone https://aur.archlinux.org/libscrypt.git
RUN cd /build && git clone https://github.com/koverstreet/bcachefs-tools.git
WORKDIR /build
