FROM fedora:32

RUN dnf groupinstall -y "Development Tools"
RUN dnf install -y \
    fuse3-devel \
    libaio-devel \
    libsodium-devel \
    libblkid-devel \
    libzstd-devel \
    zlib-devel \
    userspace-rcu-devel \
    lz4-devel \
    libuuid-devel \
    valgrind-devel \
    keyutils-libs-devel \
    libscrypt-devel

RUN dnf install -y findutils

WORKDIR /build
RUN git clone https://github.com/koverstreet/bcachefs-tools.git .
RUN make -j5 && make install
